# Generated by Django 4.1.6 on 2023-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined_on',
        ),
    ]
