from django.db import models


class DimEduc_Equipements(models.Model):
    CodeDistrict = models.IntegerField()
    NomDistrict = models.CharField(max_length=250)

    NbreCasesDesTtPetits = models.IntegerField()
    NbreGarderie = models.IntegerField()
    NbreMaternelle = models.IntegerField()
    NbrePrescoTt = models.IntegerField()
    NbreStructPrescoDisposantCantinSclre = models.IntegerField()
    NbreSCLocalNormalPresco = models.IntegerField()
    NbreSCSituationAbrisProvsrPresco = models.IntegerField()
    NbreSallesTtPresco = models.IntegerField()
    NbreStructPrescoAyantClotur = models.IntegerField()
    NbreStructPrescoAyantElectricit = models.IntegerField()
    NbreToTLatrinFonctionel = models.IntegerField()
    LatrinFonctionelGrcons = models.IntegerField()
    LatrinFonctionnelFilles = models.IntegerField()
    NbrePlacesAssises = models.IntegerField()
    NbreElevPresco = models.IntegerField()
    NbrePontEauCournt = models.IntegerField()
    NbreEnftBeneficDeparasitgMTN = models.IntegerField()
    NbreEnftBeneficieDeparasitgFER = models.IntegerField()
    NbreStructElmntaireAyantCantinScolair = models.IntegerField()
    NbreSCPrimAvecLocalNormal = models.IntegerField()
    NbreSCPrimSituationAbriProvisoir = models.IntegerField()
    NbreSallesTTPrim = models.IntegerField()
    NbreStructurAyantCloturPrim = models.IntegerField()
    TTLatrineFonctionnelPrim = models.IntegerField()
    LatrinFonctionnelGrconsPrim = models.IntegerField()
    LatrinsFonctionnelFilles = models.IntegerField()
    NbreEcolPublicAyantElectricite = models.IntegerField()
    NbreEauCourantePrim = models.IntegerField()
    NbrePlacAssisStructurPublic = models.IntegerField()
    NbrePlacAssisStructurPrive = models.IntegerField()
    NbreElvStructurPublicPrimair = models.IntegerField()
    NbreElvStructurPublicPrive = models.IntegerField()
    NbreSalleClassAvecLocalNormal = models.IntegerField()
    NbreSalleClassPrimrSituatAbriProvisoir = models.IntegerField()
    NbreSalleTotEtablisPrimPublic = models.IntegerField()
    NbreGrpPedagogicPrim = models.IntegerField()
    NbreClassePhysicPrim = models.IntegerField()
    NbreEcolEquipeSalleITPrim = models.IntegerField()
    NbreEcolPrimAyantConexionNet = models.IntegerField()
    NbreStructreAyantCatinScolreMG = models.IntegerField()
    NbreSalleClassAcLocalNormalMG = models.IntegerField()
    NbreSalleClassSituatAbriProvisoirMG = models.IntegerField()
    NbreSalleTotalMG = models.IntegerField()
    NbreStructurElmntreAyantCloturMG = models.IntegerField()
    TotLatrinFonctionnelMG = models.IntegerField()
    LatrinFonctionnelGrconsMG = models.IntegerField()
    LatrinFonctionnelFilleMG = models.IntegerField()
    NbreEcolPublicAyantElectMG = models.IntegerField()
    NbreEauCouranteMG = models.IntegerField()
    NbrePlaceAssisStructurPublicMG = models.IntegerField()
    NbrePlacAssiseStructurPrivMG = models.IntegerField()
    NbreElvStructurPublicMG = models.IntegerField()
    NbreElevStructurPrivMG = models.IntegerField()
    NbreSalleClassAvcLocalNormalMG = models.IntegerField()
    NbreGrpPedagogicMG = models.IntegerField()
    NbreClassPhysicMG = models.IntegerField()
    NbreEcolEquipSalleTIMG = models.IntegerField()
    NbreEcolAyantConnexionInetMG = models.IntegerField()
    NbreStructurAyantCatinScolreSe = models.IntegerField()
    NbreSalleClassAvecLocalNormalSecd = models.IntegerField()
    NbreSalleClassSituatAbriProvisScndre = models.IntegerField()
    NbreSallesTTSecondaire = models.IntegerField()
    NbreStructurScndrAyantClotur = models.IntegerField()
    TTLatrinFonctionnelScndr = models.IntegerField()
    LatrinGrconFonctionelScndr = models.IntegerField()
    LatrinFillesFonctionelScndr = models.IntegerField()
    NbreEcolPublicAyantElectScndr = models.IntegerField()
    NbreEauCourantScndr = models.IntegerField()
    NbrePlacAssisStructPublicScndr = models.IntegerField()
    NbrePlacAssisStructPrivScndr = models.IntegerField()
    NbreElvStructPublicScndr = models.IntegerField()
    NbreElvStructPrivScndr = models.IntegerField()
    NbreSalleDeClassAvcLocalNormalScndr = models.IntegerField()
    NbreSalleTTScndrPublic = models.IntegerField()
    NbreGrpPedagogicScndr = models.IntegerField()
    NbreClassPhysicScndr = models.IntegerField()
    NbreEcolEquipSalleITScndr = models.IntegerField()
    NbreEcolAyantConexionNetScndr = models.IntegerField()
    date = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):
        return str(self.NomDistrict)


class DimEduc_Gouvernance(models.Model):
    CodeDistrict = models.IntegerField()
    NomDistrict = models.CharField(max_length=250)

    DepensFonctionnt = models.IntegerField()
    DepensInvestis = models.IntegerField()
    MassSalarial = models.IntegerField()
    PersonelAppui = models.IntegerField()
    MassSalarialPersnlCharg = models.IntegerField()
    DepenseEnEau = models.IntegerField()
    DepensElect = models.IntegerField()
    AchatFournitScolreAidSocial = models.IntegerField()
    BeneficActivRenforcmntCapacitFP = models.IntegerField()
    DepensRenforcmntCapacitFP = models.IntegerField()
    DepensHebergtEtudts = models.IntegerField()
    NbreRecompense = models.IntegerField()
    NbreBours = models.IntegerField()
    MontanRecompens = models.IntegerField()
    MontanBourc = models.IntegerField()
    TotDepensEducat = models.IntegerField()
    DepensInvestismtEducat = models.IntegerField()
    DepensInvestismtEducat = models.IntegerField()
    MassSalarialFloat = models.DecimalField(max_digits=10, decimal_places=5)
    MassSalarialPerslChargFT = models.DecimalField(
        max_digits=10, decimal_places=5)
    AchaFournitScolairASF = models.DecimalField(
        max_digits=10, decimal_places=5)
    DepensRenforcCapacitFPF = models.DecimalField(
        max_digits=10, decimal_places=5)
    DepensHebergEtudtsFlt = models.DecimalField(
        max_digits=10, decimal_places=5)
    MontanRecompensFlt = models.DecimalField(max_digits=10, decimal_places=5)
    MontanBourceFlt = models.DecimalField(max_digits=10, decimal_places=5)
    TotDepensEducatFlt = models.DecimalField(max_digits=10, decimal_places=5)

    date = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):
        return str(self.NomDistrict)


class DimEduc_Perfomance(models.Model):
    CodeDistrict = models.IntegerField()
    NomDistrict = models.CharField(max_length=250)

    NbreNvxInscriCPAnT = models.IntegerField()
    NbreRedoublanCPAnT = models.IntegerField()
    NbreElevesCiAnneeT_1 = models.IntegerField()
    NbreNvxInscriCE1AnT = models.IntegerField()
    NbreNvxInscriCE2AnT = models.IntegerField()
    NbreNvxInscriCM1AnT = models.IntegerField()
    NbreNvxInscriCM2AnT = models.IntegerField()
    NbreRedoublanCE1AnT = models.IntegerField()
    NbreRedoublanCE2AnT = models.IntegerField()
    NbreRedoublanCM1AnT = models.IntegerField()
    NbreRedoublanCM2AnT = models.IntegerField()
    NbreElevCpAnT_1 = models.IntegerField()
    NbreElevCE1AnT_1 = models.IntegerField()
    NbreElevCE2AnT_1 = models.IntegerField()
    NbreElevCM1AnT_1 = models.IntegerField()
    NbreElevCM2AnT_1 = models.IntegerField()
    NbreNvxInscri5emAnT = models.IntegerField()
    NbreNvxInscri4emAnT = models.IntegerField()
    NbreNvxInscri3emAnT = models.IntegerField()
    NbreNvxInscri1erAnT = models.IntegerField()
    NbreNvxInscriTleAnT = models.IntegerField()
    NbreRedoublan5emAnT = models.IntegerField()
    NbreRedoublan4emAnT = models.IntegerField()
    NbreRedoublan3emAnT = models.IntegerField()
    NbreRedoublan1erAnT = models.IntegerField()
    NbreRedoublanTleAnT = models.IntegerField()
    NbreElvs6emAnT_1 = models.IntegerField()
    NbreElvs5emAnT_1 = models.IntegerField()
    Nbre4emAnT_1 = models.IntegerField()
    Nbre2ndeAnT_1 = models.IntegerField()
    NbreElev1erAnT_1 = models.IntegerField()
    NbreNvxInscriGrconCM2AnT = models.IntegerField()
    NbreNvxInscriFilleCM2AnT = models.IntegerField()
    PopJeunAge11ansAnT = models.IntegerField()
    NbreNvxInscri3emGrconAnT = models.IntegerField()
    NbreNvxInscri3emFilleAnT = models.IntegerField()
    PopJeunAge15ansAnT = models.IntegerField()
    NvxInscri6eme = models.IntegerField()
    NvxFilleInscri6em = models.IntegerField()
    NvxGrconInscri6em = models.IntegerField()
    EffectTTInscriCm2AnT_1 = models.IntegerField()
    NvxInscri2ndAnT = models.IntegerField()
    NvxGrconInscri2nd = models.IntegerField()
    NvxFilleInscri2nd = models.IntegerField()
    efectifTTInscrit3emAnT_1 = models.IntegerField()
    NbreNvxInscriTleAnT = models.IntegerField()
    NbreFilleNvxInscriTle = models.IntegerField()
    NbreGrconNvxInscriTle = models.IntegerField()
    PopJeunAge18ansAnT = models.IntegerField()
    PopJeunGrçsAge18ansAnT = models.IntegerField()
    PopJeunFille18ansAnT = models.IntegerField()
    ResultatCFEE = models.IntegerField()
    ResultatCFEE_F = models.IntegerField()
    ResultatCFEE_G = models.IntegerField()
    ResultatBFEM = models.IntegerField()
    ResultatBFEM_F = models.IntegerField()
    ResultatBfem_G = models.IntegerField()
    ResultatBac = models.IntegerField()
    ResultatBac_F = models.IntegerField()
    ResultatBac_G = models.IntegerField()
    date = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):
        return str(self.NomDistrict)


class DimEduc_Personnel(models.Model):
    CodeDistrict = models.IntegerField()
    NomDistrict = models.name = models.CharField(max_length=250)
    EnseigtPrescoPublic = models.IntegerField()
    EnseigtPrescoPrive = models.IntegerField()
    EnseigtPrescoComm = models.IntegerField()
    EnseigtPrescoTot = models.IntegerField()
    ElvsPrescoPublic = models.IntegerField()
    ElvsPrescoPrive = models.IntegerField()
    ElvsPrescoComm = models.IntegerField()
    ElvsPrescoTT = models.IntegerField()
    NbreStructPrescoAyantInfirm = models.IntegerField()
    EnseigtPrimPublic = models.IntegerField()
    EnseigtPrimPrive = models.IntegerField()
    EnseigtPrimComm = models.IntegerField()
    EnseigtPrimTT = models.IntegerField()
    ElvsPrimPublic = models.IntegerField()
    ElvsPrimPrive = models.IntegerField()
    ElvsPrimComm = models.IntegerField()
    NbreClass1MtreDonneCrscohortPrim = models.IntegerField()
    NbreClass1EnseiChargPlsrsNVPrim = models.IntegerField()
    NbreEclPPubliAyanAMInfirmiSco = models.IntegerField()
    NbreEclPPrivAyantAMInfirmSco = models.IntegerField()
    NbreEclPCommAyantAMInfirmSco = models.IntegerField()
    EnseigtPAyantDP_PCAP = models.IntegerField()
    EnseigPAyantD_CEAP = models.IntegerField()
    EnseigtPSans_DP = models.IntegerField()
    EnseigtPAyant_Bac = models.IntegerField()
    EnseigtPAyant_BFEM = models.IntegerField()
    EnseigtPAyant_CFEE = models.IntegerField()
    EnseigtPAyant_BacPs2 = models.IntegerField()
    EnseigtPAyant_Licenc = models.IntegerField()
    EnseigtPAyant_DM_DM_DEA = models.IntegerField()
    EnseigtPAyantAutre_D = models.IntegerField()
    NbreEnseigt6emA3em = models.IntegerField()
    NbreEnseigtH6emA3em = models.IntegerField()
    NbreEnseigtF6emeA3eme = models.IntegerField()
    EnsPcMGSelon_DProCAECEM = models.IntegerField()
    EnsPublicColleg_DProCAES = models.IntegerField()
    EnsPublicCollegSans_DPro = models.IntegerField()
    ElevTotMG6emA3em = models.IntegerField()
    ElevGrconMG6A3em = models.IntegerField()
    ElevFilleMoyG6emA3em = models.IntegerField()
    PerAdminfMoySecond_H = models.IntegerField()
    PersAdminMoySecond_F = models.IntegerField()
    PersAdminMoySecondTot = models.IntegerField()
    EnseigtLyceePublic = models.IntegerField()
    EnseigtLyceePrive = models.IntegerField()
    EnseigtTotLyce = models.IntegerField()
    ElevTTSecondG_2nd_Tle = models.IntegerField()
    ElevGrconSecondG_2nd_Tle = models.IntegerField()
    ElevFilleSecondG_2nd_Tle = models.IntegerField()
    NbreEnseigtTT2nd_Tle = models.IntegerField()
    NbreEnseigtH_2nd_Tle = models.IntegerField()
    NbreEnseigtFille2nd_Tles = models.IntegerField()
    NbreMedcinEtablisPulicSecond = models.IntegerField()
    NbreMedcinEtablisPriveSecond = models.IntegerField()
    NbreMedcincondTT = models.IntegerField()
    EnsPublicSecondAyan_DAcademiBAC = models.IntegerField()
    EnsPublicSecondAyan_DA_BFEM = models.IntegerField()
    EnsPublicSecondAyan_DA_CFEE = models.IntegerField()
    EnsPublicSecondAyant_Baspls2 = models.IntegerField()
    EnsPublicSecondAyan_Licenc = models.IntegerField()
    EnsPcSecondAyan_DM_DM_Plus = models.IntegerField()
    EnsPcSecondAyan_Autr_DA = models.IntegerField()
    date = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):

        return str(self.NomDistrict)


class DimEduc_Access(models.Model):

    CodeDistrict = models.IntegerField()
    NomDistrict = models.CharField(max_length=250)
    PrescoEnsGrcns3et5ans = models.IntegerField()
    PrescoEnsFilles3et5ans = models.IntegerField()
    PrescoEnsFilesEtGrcnsAge3Et5ans = models.IntegerField()
    PrescoEffectGrcnsInscritsPresco = models.IntegerField()
    PrescoEffectFilleInscritPresco = models.IntegerField()
    PrescoEffectTTInscritPresco = models.IntegerField()
    PrescoEffectPS = models.IntegerField()
    PrescoEffectMS = models.IntegerField()
    PrescoEffectGS = models.IntegerField()
    PrescoEffectTotal = models.IntegerField()
    PrescoNbreGrcnsFillesEnPS = models.IntegerField()
    PrescoNbreGrcnsFillesEnMS = models.IntegerField()
    PrescoNbreGrcnsFillesEnGS = models.IntegerField()
    PrescoNbreFillesPrescoTotal = models.IntegerField()
    PrescoEffectTTInscritPreslrePublic = models.IntegerField()
    PrescoEffecTTElvInscritsPrescoStructComm = models.IntegerField()
    PrescoEffectTTElvInscritPrecoPrive = models.IntegerField()
    PrescoEffectifTTElvFillesInscritPrecoPrive = models.IntegerField()
    PrescoEffectifTTFillesIncritStructComm = models.IntegerField()
    PrescoEffectifTTFillesAuPrescoStructComm = models.IntegerField()
    PrescoNbreTTNvxInscritsPS = models.IntegerField()
    PrescoNbreTTNvxInscritsMS = models.IntegerField()
    NbreTTNvxInscritGS = models.IntegerField()
    NbreStructurePrescoPublic = models.IntegerField()
    NbreStructurePrescolairePrive = models.IntegerField()
    NbreStructurePrescolaireComm = models.IntegerField()
    EfectlevesPrescolAyantPieceEtatCivilPS = models.IntegerField()
    EfectElvesPrescolAyantPiecEtatCivilMS = models.IntegerField()
    EfectPrecolAyantPieceEtatCivilGS = models.IntegerField()
    EfectEnfantsPrescolFrancoArabe = models.IntegerField()
    NbreDaaraModerne = models.IntegerField()
    NbreDaaraMiseAJour = models.IntegerField()
    ElNbreGarconsDe6A11ans = models.IntegerField()
    ElNbreFillesDe6A11ans = models.IntegerField()
    ElNbreEnfantsDe6A11ans = models.IntegerField()
    ElNbreEleveElmtaire = models.IntegerField()
    ElNbreGarconsElmtaire = models.IntegerField()
    ElNbreFillesElmtaire = models.IntegerField()
    ElEfectsElmtairePrive = models.IntegerField()
    ElEfectsElmtairePublic = models.IntegerField()
    ElEfectPrimStructComm = models.IntegerField()
    ElEfectsElvesPrimSituationHandicap = models.IntegerField()
    ElEfectFillesPrimSituationHandicap = models.IntegerField()
    ElEfectGarcsPrimSituationHandicap = models.IntegerField()
    ElEffectifTTElevesElementaire = models.IntegerField()
    ElEfectTTElvesPasPieceEtatCivil = models.IntegerField()
    ElEfectTTElevesCI = models.IntegerField()
    ElEfectlTTElevesCM2 = models.IntegerField()
    ElEfectEnftsPrimFrancoArabe = models.IntegerField()
    ElEfectPrimRedoublantsTotal = models.IntegerField()
    ElEfectPrimRedblantsFilles = models.IntegerField()
    ElEfectPrimRedblantGrcons = models.IntegerField()
    ElEffectifsCI = models.IntegerField()
    ElEffectifsCP = models.IntegerField()
    ElEffectifsCE1 = models.IntegerField()
    ElEffectifsCE2 = models.IntegerField()
    ElEffectifsCM1 = models.IntegerField()
    ElEffectifsCM2 = models.IntegerField()
    ElNbreRedoublantCI = models.IntegerField()
    ElNbreRedoublantCP = models.IntegerField()
    ElNbreRedoublantsCE1 = models.IntegerField()
    ElNbreRedoublantsCE2 = models.IntegerField()
    ElNbreRedoublantsCM1 = models.IntegerField()
    ElNbreRedoublantsCM2 = models.IntegerField()
    ElEfectTotalInscritElmtaire = models.IntegerField()
    ElEfectGrconsInscritElmtaire = models.IntegerField()
    ElEfectFillesIncritElmtaire = models.IntegerField()
    ElNbreElvesSituationHandicap = models.IntegerField()
    ElNbreTleElevesElmtaire = models.IntegerField()
    ElPopOfciellemntScolarbleJnes6_11ans = models.IntegerField()
    ElPopOficielemntScolarbleGrcons6_11ans = models.IntegerField()
    ElPopOficielemntScolarbleFilles6_11ans = models.IntegerField()
    ElNbreElvesQuittEtablisPourHorsComm = models.IntegerField()
    ElNbreElvesProvncEtablisSituantAutrComm = models.IntegerField()
    ElNbreEcolElmntairePublic = models.IntegerField()
    ElNbreEcolElmntairePrive = models.IntegerField()
    MGEnsbleGrconsEntre12Et15ans = models.IntegerField()
    MGEnsFillesEntre12Et15ans = models.IntegerField()
    MGNbreElvesMG = models.IntegerField()
    MGNbreElvesFilles = models.IntegerField()
    MGNbreElvesGrcons = models.IntegerField()
    MGEfectsMGPublic = models.IntegerField()
    MGEfectifMGPrive = models.IntegerField()
    MGRedblantsTotal = models.IntegerField()
    RedblantsFillesMG = models.IntegerField()
    RedblantsGrconsMG = models.IntegerField()
    EfectsInscritMGFrancoArabe = models.IntegerField()
    EffectifsMG6eme = models.IntegerField()
    EffectifsMG5eme = models.IntegerField()
    EffectifMG4e = models.IntegerField()
    EffectifMG3e = models.IntegerField()
    NbreRedoublants6e = models.IntegerField()
    NbreRedoublants5e = models.IntegerField()
    NbreRedoublants4e = models.IntegerField()
    NbreRedoublants3e = models.IntegerField()
    EfectTotalIncritMG = models.IntegerField()
    PopJeunesTranche12_15ans = models.IntegerField()
    NbreElevsEfectivmntInscrit6em1erFs = models.IntegerField()
    NbreNouvxInscritFilles6eme = models.IntegerField()
    NbreTotlNouvxInscrit6eme = models.IntegerField()
    NbreNouvxInscrit6emePublic = models.IntegerField()
    NbreElvSituationHandicapMG = models.IntegerField()
    NbreTotElvMoyGenral = models.IntegerField()
    NbreElvesMarieCrsAnnMG = models.IntegerField()
    NbreElvFillesVictimGrosseMG = models.IntegerField()
    NbreFilleVictimViolencSexuelMG = models.IntegerField()
    NbreGrconsVictimViolencSexuelMG = models.IntegerField()
    NbreFillesOrphelinMG = models.IntegerField()
    NbreTotFilleMG = models.IntegerField()
    NbreGrconsOrphelinMG = models.IntegerField()
    GrconsAge16_18ans = models.IntegerField()
    FillesAge16_18ans = models.IntegerField()
    EnsFillesGrconsAge16_18ans = models.IntegerField()
    NbreElvScdaire = models.IntegerField()
    NbreGrconsScdaire = models.IntegerField()
    NbreFillesScdaire = models.IntegerField()
    EfectScdairePublic = models.IntegerField()
    EfectScdairePrive = models.IntegerField()
    EfectScdaireCommun = models.IntegerField()
    RedblantsTotScdaireGnral = models.IntegerField()
    RedblantsFillesScdaireGnral = models.IntegerField()
    RedblantsGrconScdaire = models.IntegerField()
    Effectifs2nd = models.IntegerField()
    Effectifs1er = models.IntegerField()
    EffectifsTle = models.IntegerField()
    NbreRedblants2nd = models.IntegerField()
    NbreRedblants1er = models.IntegerField()
    NbreRedblantsTle = models.IntegerField()
    EfectTotInscritScdaire = models.IntegerField()
    PopJeunesTranch16_18ans = models.IntegerField()
    NbreElvSituationHandicapScnd = models.IntegerField()
    NbreTotElvesSecndaire = models.IntegerField()
    NbreFilleMarieEnCourAnScdaire = models.IntegerField()
    NbreElvFilleVictimGrosessScndre = models.IntegerField()
    NbreElvsVictimViolencSexuelEtablis = models.IntegerField()
    NbreFilleVictimViolencSexuelScdre = models.IntegerField()
    NbreGrconVictimViolencSexuelScdair = models.IntegerField()
    NbreElvsOrphelinScndaire = models.IntegerField()
    NbreFilleOrphelinScndaire = models.IntegerField()
    NbreGrconsOrphelinScndaire = models.IntegerField()
    NbreElvSanPieceEtatCivilScndaire = models.IntegerField()
    date = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):

        return str(self.NomDistrict)


class Visiteur (models.Model):
    nom = models.CharField(max_length=25)
    date_visiteur = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom
